services:
  nya-miner-base: &nya-miner-base
    image: nya-compute-miner:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Don't mount the app folder. This will be explicitly copied by the dockerfile so that
      # the container files live independent of the host.
      - .cache:/root/.cache # sharing model cache between host and container
      - ${HOME}/.commune:/root/.commune # sharing the key between host and container
    #    uncomment if you like to load environment variables from a file instead of setting them here
    #    env_file:
    #    - ./.example.env # in case you like to load any environment variables from a file
    working_dir: /app
    command: [ "/bin/bash", "-c", "/app/scripts/run_miner.sh" ]
  nya-miner-cpu:
    <<: *nya-miner-base
    environment:
      # Setting the environment variables used in run_miner.sh script
      - PORT=1919
      - DEVICE=cpu
      - KEY_NAME=nya-miner # change this to your key name
    ports:
      - "1919:1919"
  nya-miner-gpu:
    <<: *nya-miner-base
    environment:
      # Setting the environment variables used in run_miner.sh script
      - PORT=1920
      - DEVICE=cuda
      - KEY_NAME=nya-miner # change this to your key name
    ports:
      - "1920:1920"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

#    command: ["/bin/bash", "-c", "sleep infinity"]
#  TODO: add configs to run multiple miners on the same host
#  https://stackoverflow.com/questions/39663096/docker-compose-creating-multiple-instances-for-the-same-image
#  nya-miner-2:
#    <<: *nya-miner-1
#    environment:
#      - PORT=1920
#    ports:
#      - "1920:1920"

