services:
  nya-validator:
    image: nya-validator:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    # Don't mount the app folder. This will be explicitly copied by the dockerfile so that
    # the container files live independent of the host.
      - .cache:/root/.cache
      - ./logs:/logs
      - /root/.commune:/root/.commune
#    env_file:
#    - ./example.env
    environment:
      - PORT=8080
    ports:
      - 8080:8080
    working_dir: /app
    command: ["/bin/bash", "-c", "/app/scripts/entrypoint.sh"]